---

name: Build and deploy Collection on Ansible Galaxy
on:
  release:
    types:
      - published
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Dump env
        run: env | sort

      - name: Set version in galaxy.yml
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -re "s/^version:.*$/version: ${VERSION}/" -i galaxy.yml

      - name: galaxy.yml
        run: cat galaxy.yml

      - name: Upload collection to Ansible Galaxy
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
